import React,{useEffect,useMemo,useState}from"react";import{createRoot}from"react-dom/client";import{AvatarCall,createProxyClient,useAvatarCamera,useCharacterTools,type AvatarConnectionDetails}from"realtime-avatar/react";import"./style.css";
type Msg={role:"user"|"assistant";content:string;ts:number};type Avatar={id:string;name:string;tagline:string;status:string;poster?:string|null;idle?:string|null;kind:"human"|"character"};
const STORE="red-live-v6",DEFAULT_ID="seed-rin-ashfall";
const AVATARS:Avatar[]=[
{id:"seed-rin-ashfall",name:"Rin Ashfall",tagline:"The wanderer",status:"ready",kind:"human",poster:"https://realtimeavatar.ai/api/assets/public/characters/rin-ashfall/portrait.png",idle:"https://realtimeavatar.ai/api/assets/public/characters/rin-ashfall/idle-10s.mp4"},
{id:"seed-vesper-nyx",name:"Vesper Nyx",tagline:"The blade",status:"ready",kind:"human",poster:"https://realtimeavatar.ai/api/assets/public/characters/vesper-nyx/portrait.png"},
{id:"seed-professor-thistle",name:"Professor Thistle",tagline:"The mentor",status:"ready",kind:"character",poster:"https://realtimeavatar.ai/api/assets/public/characters/professor-thistle/portrait.png"},
{id:"seed-valko",name:"Valko",tagline:"The wolf",status:"ready",kind:"character",poster:"https://realtimeavatar.ai/api/assets/public/characters/valko/portrait.png"},
{id:"seed-remy",name:"Remy",tagline:"The debater",status:"ready",kind:"human",poster:"https://realtimeavatar.ai/api/assets/public/characters/remy/portrait.png"},
{id:"seed-koko",name:"Koko",tagline:"The warmth",status:"ready",kind:"character",poster:"https://realtimeavatar.ai/api/assets/public/characters/koko/portrait.png"},
{id:"seed-luciano-draven",name:"Luciano Draven",tagline:"The anti-hero",status:"ready",kind:"human",poster:"https://realtimeavatar.ai/api/assets/public/characters/luciano-draven/portrait.png"}];
const DEFAULT_AVATAR=AVATARS[0];function read(){try{return JSON.parse(localStorage.getItem(STORE)||"{}")}catch{return{}}}
function Web(){const t=useCharacterTools({web_search:{description:"Search the live web for current information. Never guess current facts.",parameters:{type:"object",properties:{query:{type:"string"}},required:["query"]},execute:async({query}:{query:string},{signal})=>{const r=await fetch("/api/web-search?q="+encodeURIComponent(query),{signal}),d=await r.json();if(!r.ok)throw new Error(d?.error||"Search failed");return JSON.stringify((d.results||[]).slice(0,6))}}});return <span className={"toolStatus "+t.status}>WEB {t.status==="ready"?"LIVE":t.status.toUpperCase()}</span>}
function Camera({active}:{active:boolean}){const c=useAvatarCamera({allowed:true,active});return <button className="miniButton"disabled={!c.available}onClick={()=>void c.toggle()}>{c.enabled?"Camera on":c.pending?"Opening…":"Camera"}</button>}
function App(){const s=read();const[avatarId,setAvatarId]=useState(s.avatarId||DEFAULT_ID),[selected,setSelected]=useState<Avatar>(s.selected||DEFAULT_AVATAR),[avatars,setAvatars]=useState<Avatar[]>(AVATARS),[status,setStatus]=useState(s.status||"ready"),[inCall,setInCall]=useState(false),[error,setError]=useState(""),[connection,setConnection]=useState<AvatarConnectionDetails|null>(null),[messages,setMessages]=useState<Msg[]>(s.messages||[]),[memory,setMemory]=useState(s.memory||""),[text,setText]=useState(""),[modal,setModal]=useState<"memory"|"create"|"web"|"settings"|null>(null),[notice,setNotice]=useState(""),[name,setName]=useState("RED"),[motion,setMotion]=useState("Natural breathing, attentive eye contact, subtle head movement, expressive listening and restrained conversational gestures."),[portrait,setPortrait]=useState(""),[busy,setBusy]=useState(false),[query,setQuery]=useState(""),[results,setResults]=useState<any[]>([]);const client=useMemo(()=>createProxyClient({proxyUrl:"/api/realtime-avatar"}),[]);
useEffect(()=>localStorage.setItem(STORE,JSON.stringify({avatarId,selected,status,messages,memory})),[avatarId,selected,status,messages,memory]);
useEffect(()=>{fetch("/api/avatars").then(r=>r.json()).then(d=>{if(!Array.isArray(d.avatars))return;const m=new Map(AVATARS.map(a=>[a.id,a]));d.avatars.forEach((a:any)=>{if(!a?.id||/mark zuckerberg/i.test(a.name))return;const old=m.get(a.id);m.set(a.id,{id:String(a.id),name:String(a.name||old?.name||"Live character"),tagline:old?.tagline||"Live character",status:String(a.status||"unknown"),kind:old?.kind||"human",poster:a.poster||old?.poster||null,idle:a.idle||old?.idle||null})});setAvatars([...m.values()])}).catch(()=>{})},[]);
useEffect(()=>{if(!avatarId.startsWith("ava_"))return;let stop=false;const p=async()=>{try{const d=await(await fetch("/api/avatar/status?id="+encodeURIComponent(avatarId))).json();if(!stop){setStatus(d.status||"unknown");setSelected(a=>({...a,status:d.status||a.status,poster:d.posterUrl||a.poster,idle:d.idleVideoUrl||a.idle}))}}catch{}};p();const t=setInterval(p,10000);return()=>{stop=true;clearInterval(t)}},[avatarId]);
const select=(a:Avatar)=>{if(inCall)return;setAvatarId(a.id);setStatus(a.status);setSelected(a);setError("")};
const send=async()=>{const v=text.trim();if(!v)return;setText("");const next=[...messages,{role:"user"as const,content:v,ts:Date.now()}];setMessages(next);try{const r=await fetch("/api/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:v,messages:next,memory,avatar:selected.name})}),d=await r.json();if(!r.ok)throw 0;setMessages(m=>[...m,{role:"assistant",content:d.reply||"",ts:Date.now()}])}catch{setMessages(m=>[...m,{role:"assistant",content:"Start the live conversation for hands-free voice and the talking avatar.",ts:Date.now()}])}};
const choose=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;if(!/^image\/(png|jpeg|webp)$/.test(f.type)||f.size>8*1024*1024){setNotice("Use PNG, JPEG or WebP up to 8 MB.");return}const r=new FileReader();r.onload=()=>setPortrait(String(r.result));r.readAsDataURL(f)};
const create=async()=>{const f=(document.getElementById("portrait")as HTMLInputElement)?.files?.[0];if(!f){setNotice("Choose a portrait first.");return}setBusy(true);try{const fd=new FormData();fd.append("file",f);fd.append("name",name);fd.append("motionPrompt",motion);const r=await fetch("/api/avatar/create",{method:"POST",body:fd}),d=await r.json();if(!r.ok)throw new Error(d.error||"Avatar creation failed");const a:Avatar={id:d.id,name:d.displayName||name,tagline:"Your AI character",status:d.status||"preprocessing",kind:"human",poster:d.posterUrl||portrait,idle:d.idleVideoUrl};setAvatars(v=>[a,...v.filter(x=>x.id!==a.id)]);select(a);setNotice("Character creation started. It becomes live when rendering is ready.")}catch(e){setNotice(e instanceof Error?e.message:"Avatar creation failed")}finally{setBusy(false)}};
const save=async()=>{try{const r=await fetch("/api/memory",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({memory,messages})});if(!r.ok)throw 0;setNotice("Memory saved.")}catch{setNotice("Memory could not be saved.")}};
const search=async()=>{if(!query.trim())return;setBusy(true);try{const r=await fetch("/api/web-search?q="+encodeURIComponent(query)),d=await r.json();if(!r.ok)throw new Error(d.error||"Search failed");setResults(d.results||[])}catch(e){setNotice(e instanceof Error?e.message:"Search failed")}finally{setBusy(false)}};
const poster=selected.poster||portrait||DEFAULT_AVATAR.poster,idle=selected.idle||(selected.id===DEFAULT_ID?DEFAULT_AVATAR.idle:undefined);
return <div className="appShell"><header className="topbar"><div className="brand"><div className="brandMark">R</div><div><strong>RED <i>LIVE</i></strong><small>LIVE AI CHATS UNLEASHED</small></div></div><div className="topActions"><span className="online"><b/> SYSTEM READY</span><button className="glassButton"onClick={()=>setModal("settings")}>Settings</button></div></header><main>
<section className="homeArtwork"><div className="homeArtworkCopy"><div className="kicker">RED LIVE · OFFICIAL VISUALS</div><h2>The RED LIVE experience, right on the home screen.</h2><p>The two cinematic RED LIVE visuals are now front-and-centre — the official host artwork and the full face-to-face AI showcase.</p></div><div className="homeArtworkGrid"><figure><img src="/assets/red-live-hero.webp" alt="RED LIVE official cinematic host artwork"/><figcaption><b>RED LIVE Host</b><span>Official cinematic visual</span></figcaption></figure><figure><img src="/assets/red-live-showcase.webp" alt="RED LIVE official face-to-face AI showcase artwork"/><figcaption><b>Face-to-face AI</b><span>Voice · memory · camera · web</span></figcaption></figure></div></section>
<section className="hero"><div className="heroCopy"><div className="kicker">FACE-TO-FACE AI</div><h1>Talk to AI<br/><span>like it’s actually there.</span></h1><p>Interruptible voice. Lifelike video. Memory. Live web access. Camera when you want it. One conversation that keeps going.</p><div className="heroButtons">{!inCall?<button className="primaryButton"disabled={status!=="ready"}onClick={()=>{setError("");setInCall(true)}}>{status==="ready"?"START LIVE CONVERSATION":"AVATAR "+status.toUpperCase()}</button>:<button className="dangerButton"onClick={()=>setInCall(false)}>END LIVE CONVERSATION</button>}<button className="outlineButton"onClick={()=>setModal("create")}>Create an avatar</button></div><div className="trustRow"><span>● FULL DUPLEX</span><span>● REAL-TIME VIDEO</span><span>● WEB TOOLS</span><span>● MEMORY</span></div></div>
<div className="heroStage"><div className="stageChrome"><span><b/> {inCall?"LIVE NOW":"READY"} · {selected.name}</span><Web/></div><div className={"stageMedia "+(inCall?"isLive":"isIdle")}>{inCall?<AvatarCall client={client} avatarId={avatarId} poster={poster||undefined} idleVideoUrl={idle||undefined} style={{width:"100%",height:"100%"}} onStatusChange={s=>{if(s==="live")setError("")}} onConnectionDetailsChange={setConnection} onEnded={({reason})=>{setInCall(false);setError(reason?String(reason):"The session ended.");setConnection(null)}}>{call=><div className="callOverlay"><div className="callInfo"><strong>{call.status==="waiting"?"IN QUEUE · "+call.queuePosition:call.status.toUpperCase()}</strong>{connection?.localQuality&&<small>{connection.localQuality}</small>}</div><div className="callControls"><Camera active={inCall}/><button className="endPill"onClick={call.end}>End</button></div></div>}</AvatarCall>:idle?<video className="avatarMedia"src={idle}poster={poster||undefined}autoPlay muted loop playsInline/>:poster?<img className="avatarMedia"src={poster}alt={selected.name}/>:<div className="emptyAvatar">{selected.name}</div>}<div className="portraitGlow"/><div className="namePlate"><strong>{selected.name}</strong><span>{selected.tagline} · {status==="ready"?"LIVE READY":status}</span></div></div>{error&&<div className="callError"><b>Connection ended</b><span>{error}</span><button onClick={()=>setError("")}>Dismiss</button></div>}</div></section>
<section className="cinematicShowcase"><div className="showcaseHead"><div><div className="kicker">RED LIVE VISUAL SYSTEM</div><h2>Designed to feel alive before you even speak.</h2><p>Local cinematic artwork, animated lighting and motion layers now reinforce the live-avatar experience.</p></div><span className="showcaseBadge">CINEMATIC UI</span></div><div className="showcaseGrid"><figure className="showcaseTile heroArt"><img src="/assets/red-live-hero.webp" alt="RED LIVE cinematic host artwork"/><figcaption><b>RED LIVE Host</b><span>Hero visual · animated glow</span></figcaption></figure><figure className="showcaseTile"><img src="/assets/red-live-showcase.webp" alt="RED LIVE feature overview"/><figcaption><b>Face-to-face AI</b><span>Voice · memory · camera · web</span></figcaption></figure></div></section>
<section className="vault"><div className="sectionIntro"><div><div className="kicker">CHARACTER VAULT</div><h2>Pick who you want to talk to.</h2><p>Seven polished live characters are ready now. Every one uses the same voice, memory, camera and live-web layer.</p></div><button className="outlineButton"onClick={()=>setModal("create")}>＋ CREATE YOUR OWN</button></div><div className="avatarGrid">{avatars.map(a=><button key={a.id}className={"avatarCard "+(a.id===avatarId?"selected":"")}onClick={()=>select(a)}><div className="cardImage animatedPortrait">{a.id===DEFAULT_ID&&a.idle?<video src={a.idle}poster={a.poster||undefined}muted autoPlay loop playsInline/>:a.poster?<img src={a.poster}alt={a.name}/>:<div className="avatarFallback">{a.name[0]}</div>}<span className="cardKind">{a.kind==="character"?"CHARACTER":"HUMAN"}</span></div><div className="cardText"><strong>{a.name}</strong><span>{a.tagline}</span><small><i/> {a.status==="ready"?"LIVE READY":a.status.toUpperCase()}</small></div></button>)}<button className="avatarCard createCard"onClick={()=>setModal("create")}><div className="plus">＋</div><strong>Build your own</strong><span>Portrait → animated live character</span></button></div></section>
<section className="chatPanel"><div className="chatHead"><div><div className="kicker">ALWAYS-ON TEXT</div><h2>Keep the conversation going.</h2></div><button className="glassButton"onClick={()=>setModal("memory")}>Memory</button></div><div className="messages">{messages.length?messages.map((m,i)=><div className={"message "+m.role}key={i}><small>{m.role==="user"?"YOU":selected.name.toUpperCase()}</small><div>{m.content}</div></div>):<div className="emptyChat">Text chat is here when you want a quieter conversation.</div>}</div><div className="composer"><input value={text}onChange={e=>setText(e.target.value)}onKeyDown={e=>e.key==="Enter"&&send()}placeholder={"Message "+selected.name+"…"} /><button onClick={send}>SEND</button></div></section><nav className="bottomNav"><button onClick={()=>setModal("memory")}>Memory</button><button onClick={()=>setModal("create")}>Create</button><button onClick={()=>setModal("web")}>Web search</button><button onClick={()=>setModal("settings")}>Settings</button></nav></main>
{modal==="create"&&<div className="modal"><div className="sheet"><button className="close"onClick={()=>setModal(null)}>×</button><div className="kicker">AVATAR STUDIO</div><h2>Make one that feels yours.</h2><p>Upload a clear portrait. The live-avatar engine turns the still image into an animated conversational character.</p><input id="portrait"type="file"accept="image/png,image/jpeg,image/webp"onChange={choose}/>{portrait&&<img className="preview"src={portrait}alt="Portrait preview"/>}<input value={name}onChange={e=>setName(e.target.value)}placeholder="Character name"/><textarea value={motion}onChange={e=>setMotion(e.target.value)}/><button className="primaryButton wide"disabled={busy}onClick={create}>{busy?"BUILDING…":"CREATE LIVE AVATAR"}</button>{notice&&<div className="notice">{notice}</div>}</div></div>}
{modal==="memory"&&<div className="modal"><div className="sheet"><button className="close"onClick={()=>setModal(null)}>×</button><div className="kicker">MEMORY</div><h2>Keep the important stuff.</h2><p>Saved memory stays in this browser and is supplied as context to the live session.</p><textarea value={memory}onChange={e=>setMemory(e.target.value)}placeholder="Preferences, projects, ongoing ideas…"/><button className="primaryButton wide"onClick={save}>SAVE MEMORY</button>{notice&&<div className="notice">{notice}</div>}</div></div>}
{modal==="web"&&<div className="modal"><div className="sheet"><button className="close"onClick={()=>setModal(null)}>×</button><div className="kicker">LIVE WEB</div><h2>Search what’s current.</h2><div className="searchRow"><input value={query}onChange={e=>setQuery(e.target.value)}onKeyDown={e=>e.key==="Enter"&&search()}placeholder="Search the live web…"/><button onClick={search}disabled={busy}>SEARCH</button></div><div className="results">{results.map((r:any)=><article key={r.url}><a href={r.url}target="_blank"rel="noreferrer">{r.title}</a><p>{r.snippet}</p></article>)}</div>{notice&&<div className="notice">{notice}</div>}</div></div>}
{modal==="settings"&&<div className="modal"><div className="sheet"><button className="close"onClick={()=>setModal(null)}>×</button><div className="kicker">SYSTEM</div><h2>RED LIVE</h2><div className="settingLine"><span>Selected</span><b>{selected.name}</b></div><div className="settingLine"><span>Status</span><b>{status}</b></div><div className="settingLine"><span>Web</span><b>Live search enabled</b></div><div className="settingLine"><span>Camera</span><b>Available in live call</b></div><button className="outlineButton wide"onClick={()=>fetch("/api/live-diagnostic").then(r=>r.json()).then(d=>setNotice(JSON.stringify(d))).catch(()=>setNotice("Provider diagnostic failed"))}>RUN LIVE DIAGNOSTIC</button>{notice&&<div className="notice">{notice}</div>}</div></div>}</div>}
createRoot(document.getElementById("root")!).render(<App/>);